package com.example.jdbcdemo.service;

import java.sql.Connection;
import java.sql.Statement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;

public class GunService {
	
	private final String URL = "jdbc:hsqldb:hsql://localhost/workdb";
	private final String CREATE_TABLE_SQL = "CREATE TABLE Gun(id bigint GENERATED BY DEFAULT AS IDENTITY, name varchar(20) UNIQUE, type varchar(20), productionDate date, damaged boolean, weight double)";
	
	private static Connection connection;
	private static Statement statement;
	
	public GunService() throws SQLException {
		
		connection = DriverManager.getConnection(URL);
		statement = connection.createStatement();
		
		ResultSet rs = connection.getMetaData().getTables(null, null, null, null);
		
		boolean tableExists = false;
		while(rs.next()) {
			if("Gun".equalsIgnoreCase(rs.getString("table_name"))) {
				tableExists = true;
				break;
			}
		}
		
		if(!tableExists) statement.executeUpdate(CREATE_TABLE_SQL);
	}
	
	public void addGun(String name, String type, String productionDate, boolean damaged, double weight) throws SQLException {
		statement.executeUpdate("INSERT INTO Gun(name, type, productionDate, damaged, weight) VALUES ('"+name+"','"+type+"','"+productionDate+"',"+damaged+",'"+weight+"')");
	}

	public static void main(String[] args) throws SQLException {
		GunService gs = new GunService();
		gs.addGun("Glock", "9mm", "2016-09-11", false, 0.85);
	}

}
